const express = require('express')
const router = express.Router()
const register = require('./register')
const login = require('./login')
const logout = require('./logout')
const updateNote = require('./updateNote')
const createNote = require('./createNote')
const deleteNote = require('./deleteNote')
const isLogged = require('./isLogged')
const getNotes = require('./getNote')
router.post('/register', register)
router.post('/login', login)
router.post('/createNote', createNote)
router.post('/updateNote', updateNote)
router.post('/deleteNote', deleteNote)
router.get('/logout', logout)
router.get('/isLogged', isLogged)
router.get('/getNotes', getNotes)
module.exports = router